os: Visual Studio 2015
version: "{build}"
build: off
platform: x64
environment:
  matrix:
  - nodejs_version: "10"
  - nodejs_version: "12"
  - nodejs_version: "14"
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install
test_script:
  - npm test
