on:
  - push
  - pull_request
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            nodejs_version: 10
            prebuild: true
          - os: ubuntu-20.04
            nodejs_version: 12
          - os: ubuntu-20.04
            nodejs_version: 14
          - os: ubuntu-20.04
            nodejs_version: 15
          - os: ubuntu-20.04
            container: node:10-alpine3.12
            prebuild: true
          - os: ubuntu-20.04
            container: node:12-alpine3.12
          - os: ubuntu-20.04
            container: node:14-alpine3.12
          - os: ubuntu-20.04
            container: node:15-alpine3.12
          - os: macos-10.15
            nodejs_version: 10
            prebuild: true
          - os: macos-10.15
            nodejs_version: 12
          - os: macos-10.15
            nodejs_version: 14
          - os: macos-10.15
            nodejs_version: 15
          - os: windows-2019
            nodejs_version: 10
            prebuild: true
          - os: windows-2019
            nodejs_version: 12
          - os: windows-2019
            nodejs_version: 14
          - os: windows-2019
            nodejs_version: 15
    steps:
      - name: Dependencies (Linux musl)
        if: contains(matrix.container, 'alpine')
        run: apk add build-base git python3 --update-cache
      - name: Dependencies (Linux glibc, macOS, Windows)
        if: contains(matrix.container, 'alpine') != true
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs_version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm install --build-from-source --unsafe-perm
      - name: Test
        run: npm test
      - name: Prebuild
        if: matrix.prebuild && startsWith(github.ref, 'refs/tags/')
        env:
          prebuild_upload: ${{ secrets.GITHUB_TOKEN }}
        run: npx prebuild --runtime napi --target 3
